### ISSUE TITLE
rime-outを生成せずに実行するオプション

### ISSUE THREAD

**Issue by not522** [icpc-jag/rime#13]
Dropbox上でrimeを走らせると大変なことになるので、rime-outを生成せずに実行できるオプションが欲しい。
単に/tmpなどにrime-outを作るのでも良さそう。

**Comment by hiroshi-cl** [comment]
`--outDir` を作ろう

**Comment by hiroshi-cl** [comment]
rime-outなしに意味があるrimeのコマンドってありましたっけ？
特定のディレクトリでrimeコマンドを打ったときにrimeを走らせないようにすることが重要なんですね？
起動オプションよりは、特定のディレクトリと紐づくように RIME_STOP みたいな名前のファイルがあったら走らせないとかが良さそうな気がします。
(レポジトリが汚染されないよう.gitignoreで無視することもできますね

**Comment by not522** [comment]
rime testはしたいが、rime-outが出来ると邪魔というケースを想定してます。
Dropbox上での実行がこれに該当して、通信が大変なことになる・複数人が同時に実行して壊れるという話を聞いたことがあります。

**Comment by hiroshi-cl** [comment]
コンパイル済みコードやテストケースなどのファイルがないといけないのでrime-out自体は作らないといけませんね。これはrime-outの場所を適切な場所に動かせるようにするというissueですね

**Comment by not522** [comment]
そうですね、--outDirが妥当な解決策だと思います。
PROJECTの全ての問題に対して走らせる時は
/tmp/A/rime-out
/tmp/B/rime-out
...
のようになれば良さそうですね。
