### ISSUE TITLE
誤答のステータスを指定したい

### ISSUE THREAD

**Issue by not522** [icpc-jag/rime#15]
TLE解がWAになった場合にエラーを出したい
SOLUTIONで expected_status=['AC','TLE'] と書ければ良さそう

**Comment by hiroshi-cl** [comment]
SOLUTION に `expected_status=['AC','TLE']` を追加する方は _WrapSolution をちょっと書き換えればすぐできそう。あとは `_TestSolutionWithChallengeCasesOne` あたりをいじってロジックを追加すればできそう

**Comment by hiroshi-cl** [comment]
`expected_score` と同じように実装したほうが楽そうでした
