### ISSUE TITLE
使用するコンパイラを指定したい

### ISSUE THREAD

**Issue by arosh** [icpc-jag/rime#16]
Macにhomebrewでgccをインストールして使っているので，いつもインストール後に basic/codes.py を直接編集して gcc -> gcc-7, g++ -> g++-7 と書き換えているのですが `.rimerc` のような設定ファイルに書けるようになると嬉しいです。

**Comment by hiroshi-cl** [comment]
今の rime の実装的にその .rimerc の設定を渡す穴を開けるのはあまり簡単じゃなさそうですね。。
なんか良い設計考えてみます
